### ISSUE TITLE
It will have some problem, when I use it in transparent background image.

### ISSUE THREAD

**Issue by FiShelly** [sapics/scale.js#1]
It happened in transparent background image(.png)
Such as this image:
![image](https://user-images.githubusercontent.com/16427792/102441844-10545d80-405e-11eb-9da9-302f4251036b.png)
when i call:
```
const newCanvas = scale({
      scaleX: this.outputWidth / this.originWidth,
      scaleY: this.outputHeight / this.originHeight
}, canvas);
```
It will return new canvas which the background is black. 
So can you help me to solve it? 
Thx.

**Comment by sapics** [comment]
@FiShelly I look into this issue :)
Which program do you use, scale.min.js or scale-nonalpha.min.js? If you want to work with transparent images like png, you need to use scale.min.js.

**Comment by FiShelly** [comment]
> @FiShelly I look into this issue :)
> Which program do you use, scale.min.js or scale-nonalpha.min.js? If you want to work with transparent images like png, you need to use scale.min.js.

Oh!!!
 I got it.
I do not set **HAS_ALPHA**.
Thx so much.

**Comment by sapics** [comment]
The problem seems to be resolved, so I will close this issue.
If you have any additional problems, you can reopen this issue.
